name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build with Maven
        run: mvn clean package

      - name: Log in to Docker Hub
        run: echo "${{ DOCKER_HUB_PASSWORD }}" | docker login -u "${{ DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t app .

      - name: Push Docker image
        run: docker push ${{ DOCKER_HUB_USERNAME }}/demo:latest

      - name: Deploy Docker container
        run: |
          docker run -d -p 8080:8080 \
          -e DOCKER_HUB_USERNAME=nndieu88@gmail.com
          -e DOCKER_HUB_PASSWORD=Nndieu@123
          -e spring.datasource.url=jdbc:mysql://host.docker.internal:3006/myDb?createDatabaseIfNotExist=true
          --name application ${{ DOCKER_HUB_USERNAME }}/demo:latest